### ISSUE TITLE
POST /api/v1/courses	

### ISSUE THREAD

**Issue by Phpp1010** [thm-mni-ii/submissioncheck#168]
@bees4ever Creating a course should give response like

```
{success: true || false}
```

**Comment by bees4ever** [comment]
@Phpp1010 Do you really do not want to have the created course id? Because this could be useful, sometime. So before I disable this, I want an approval and then I will do it.

If there is an error, you will get an error code, otherwise Status Code 200 or 201 shows success.

But however, after an approval, I will change this.

**Comment by bees4ever** [comment]
I will send both
