### ISSUE TITLE
Send bash file with kafka to docker

### ISSUE THREAD

**Issue by bees4ever** [thm-mni-ii/submissioncheck#54]
We need to provide test file (i.e. bash files) in our Webservice. Then we can send these URLs to a running docker instance.

**Comment by bees4ever** [comment]
Hi @vlad-sokyrsky, I send now a url via kafka to the secrettoken checker instance.

The new request locks like this:

```JavaScript
{
  "testfile_url" : "localhost:8080/api/v1/tasks/3/files/bash1.sh",
  "data" : "7774ffd6f676ab7f4e17c0f38c7d5d8d",
  "userid" : "bmnn57",
  "taskid" : "3",
  "submissionid" : "60"
}
```

Do you implement this on the secrettoken-checker side os should I implement this?

**Comment by vlad-sokyrsky** [comment]
Yes I would implement the st-checker side.
A problem I see is that for every submission the files are being downloaded again.

**Comment by vlad-sokyrsky** [comment]
Maybe we should use another request for opening a task (sent by the professor)
and include files there?

**Comment by bees4ever** [comment]
@vlad-sokyrsky:  Great idea. We can do this, I send `taskid` and `url` to docker. How should we call this topic, maybe "new_task_request"? Or do you have another idea?

**Comment by vlad-sokyrsky** [comment]
"new_task_request" is fine.
I would also include `userid` (for potential verification)
and a `courseid` if possible

**Comment by vlad-sokyrsky** [comment]
I agree that we need to expand on kafka topics. Using different topics for different feedback instances makes sense. Like "sql_submission_request" or "st_create_task" for example. 
I think extra JSON fields should be used for specifying things like "is the submission a String or is it a file?"

**Comment by vlad-sokyrsky** [comment]
Sorry for the delay..
I agree that we need to expand on kafka topics. Using different topics for different feedback instances makes sense. Like "sql_submission_request" or "st_create_task" for example. 
I think extra JSON fields should be used for specifying things like "is the submission a String or is it a file?" so that the message can be mapped correctly

**Comment by vlad-sokyrsky** [comment]
Sorry for the delay..
I agree that we need to expand on kafka topics. Using different topics for different feedback instances makes sense. Like "sql_submission_request" or "st_create_task" for example. 
I think extra JSON fields should be used for specifying things like "is the submission a String or is it a file?" so that the message can be mapped correctly

**Comment by bees4ever** [comment]
@vlad-sokyrsky: I now implemented in the WS that each testsystem has its own topic. So for instance for Secret Token Checker we have: `secrettokenchecker_check_answer` and `secrettokenchecker_check_request`.

That means we can use a standart action name but with the prefix of a system wide unique test-system short name. What do you think?

**Comment by vlad-sokyrsky** [comment]
We should use those prefixes, I agree.
I will have to get back to you tomorrow for the sending and saving of files and so on. Sadly I dont have more time today.

**Comment by bees4ever** [comment]
From a submission the SecretTokenChecker gets an extra field via Kafka called `submit_typ`. which can be `file` or `data`. Example
````JavaScript
{
  "fileurl" : "https://localhost:8080/api/v1/tasks/10/files/submissions/132/8a616023206bd2c21a4385570b33aaeb8ec0a481",
  "submit_typ" : "file",
  "userid" : "blastudent",
  "taskid" : "10",
  "submissionid" : "132"
}

````
